# SPDX-FileCopyrightText: 2023 - 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Valkey installation tasks
  block:
    - name: Validate Valkey configuration
      when: valkey_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Valkey
      when: valkey_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-valkey
    - install-all
    - install-valkey

- name: Perform Valkey uninstallation tasks
  block:
    - name: Uninstall Valkey
      when: not valkey_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-valkey
