# SPDX-FileCopyrightText: 2023 - 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Valkey installation tasks
  when: valkey_enabled | bool
  tags:
    - setup-all
    - setup-valkey
    - install-all
    - install-valkey
  block:
    - name: Validate Valkey configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Valkey
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Valkey uninstallation tasks
  when: not valkey_enabled | bool
  tags:
    - setup-all
    - setup-valkey
  block:
    - name: Uninstall Valkey
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
